### ISSUE TITLE
hybrid_test.dart passes despite throwing unhandled exceptions

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/test#1007]
I noticed in the console that this test throws an unhandled exception, despite passing.

To reproduce, this this test as `solo: true`:

https://github.com/dart-lang/test/blob/e7628f9ce97badf1b0e466b4c253aae8f28c3ce4/pkgs/test/test/runner/hybrid_test.dart#L126-L139

Run it: `pub run test test/runner/hybrid_test.dart`

Observe the following output:

```
nhandled exception:
oh no!
unparsed                                                 #0      hybridMain (<data:application/dart>:4:11)
package:test_core/src/runner/hybrid_listener.dart 66:13  listen.<fn>.<fn>
dart:async/zone.dart 1124:13                             _rootRun
dart:async/zone.dart 1021:19                             _CustomZone.run
dart:async/zone.dart 1516:10                             _runZoned
dart:async/zone.dart 1463:12                             runZoned
package:test_core/src/runner/hybrid_listener.dart 39:5   listen.<fn>
package:stack_trace/src/chain.dart 101:24                Chain.capture.<fn>
dart:async/zone.dart 1124:13                             _rootRun
dart:async/zone.dart 1021:19                             _CustomZone.run
dart:async/zone.dart 1516:10                             _runZoned
dart:async/zone.dart 1463:12                             runZoned
package:stack_trace/src/chain.dart 99:12                 Chain.capture
package:test_core/src/runner/hybrid_listener.dart 38:9   listen
unparsed                                                 #14     main (<data:application/dart>:5:36)
dart:isolate/runtime/libisolate_patch.dart 296:32        _startIsolate.<fn>
dart:isolate/runtime/libisolate_patch.dart 171:12        _RawReceivePortImpl._handleMessage
00:01 +1: All tests passed!
```

**Comment by natebosch** [comment]
This seems like it is by design, the error is being surfaced through the `StreamChannel` which is handling the error (expecting it in this case). If you either don't handle the errors on that channel, or fail the test if they come through, then the overall test should fail.

I think what we want to focus on is having these _not_ behave as if they are unhandled, because they are already forwarded somewhere where they'd need to be handled. We don't need to worry about the truncated output since there won't be any output anymore.
