### ISSUE TITLE
MyProgram depends on both test ^1.6.9 and flutter_test any from sdk, version solving failed.

### ISSUE THREAD

**Issue by ride4sun** [dart-lang/test#1072]
I updated to flutter 1.9 and Dart 2.5 and I get this error message and don't know how to solve it.
MyProgram depends on both test ^1.6.9 and flutter_test any from sdk, version solving failed.

Here the longer version: 
Because every version of flutter_test from sdk depends on test_api 0.2.5 and tes
t >=1.6.8 depends on test_api 0.2.7, flutter_test from sdk is incompatible with
test >=1.6.8.
So, because obdchk depends on both test ^1.6.9 and flutter_test any from sdk, ve
rsion solving failed.
Running "flutter pub upgrade" in obdchk...
pub upgrade failed (1)

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.356], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Community Edition (version 2017.3)
[√] VS Code, 32-bit edition (version 1.30.1)
[√] Connected device (1 available)

• No issues found!

C:\Projects\obdchk>

**Comment by jakemac53** [comment]
This is not actually an issue with the `test` package itself - the problem here is that `flutter_test` doesn't support the latest `package:test`.

I would file an issue on flutter to update their version constraint on `test_api`.

Alternatively you can change your `test` dependency to allow earlier versions, or if `obdchk` is one of your deps you might need to allow an earlier version of that.

You can also try adding a dependency override to see if things in fact work:

```
dependency_overrides:
  test_api: ^0.2.7
```

**Comment by ride4sun** [comment]
Thanks that worked. Filed a defect: https://github.com/flutter/flutter/issues/40615
