### ISSUE TITLE
Watch mode

### ISSUE THREAD

**Issue by vargavince91** [dart-lang/test#1093]
Is "watch" mode supported by this library? I checked the docs and didn't find anything that looked like the "watch" mode that is supported by, for example, Jest (JavaScript testing framework).

* Jest https://jestjs.io/docs/en/cli

Are you planning to support it?

I'd like to be able to just type:

```
pub run test --watch .
```

And as I edit my test files and program files (the ones being tested), I want the test to restart. Ideally, the command should be clever enough to figure out which files changed and based on this, it should decide which suites should be re-run.

**Comment by grouma** [comment]
As of today we do not unfortunately have an automatic test runner. We are in the process of open sourcing a tool called Bolt which would satisfy this request.

cc @liuming0

**Comment by vargavince91** [comment]
@grouma That would be awesome! Are you going to open-source it separately, or take parts and add it to the `test` package?

**Comment by natebosch** [comment]
It will most likely be separate from the test package. We don't have an idea of timeline for now.

cc @jakemac53 - I wonder how how it would be to introduce a watch mode through `buidld_runner test`? Or with the build daemon?

**Comment by jakemac53** [comment]
It wouldn't be that difficult really, but we don't have any work currently planned.

**Comment by jakemac53** [comment]
Note also that while we could do something basic here we don't have the expressiveness currently to be totally correct. We can re-run if any transitive dart file changes for the test but not if a data file changes.

**Comment by evanweible-wf** [comment]
Is that something you'd accept a contribution for? We may have some bandwidth in the near future to help out, but would probably need to be pointed in the right direction.

> but not if a data file changes.
Does this mean something the build system isn't aware of? Or just anything that isn't a dart file?

Also, would this watch mode re-run all the tests? Or would it create a separate merged output directory with only the changed outputs?

**Comment by jakemac53** [comment]
Correct, the build system is only aware of inputs/outputs, it doesn't understand runtime dependencies such as golden files.

So for example we can re-run tests by checking if the resulting `.app.dill` file is in the build outputs (if so it needs to be re-ran), but if that file happens to read a golden file then we won't know to re-run the test when the golden changes but the kernel file didn't change.

**Comment by jakemac53** [comment]
One way to solve this long term is to treat running a test conceptually as just another build step. That would mean re-writing tests to not use `dart:io` though and use the build step apis - although we might be able to use the `IoOverrides` class to handle this automatically? This would also potentially resolve problems around reading generated files in tests.

**Comment by robbecker-wf** [comment]
Anything to be done here in the short term? Iterating on tests is a large pain point.

**Comment by jakemac53** [comment]
We aren't doing anything here in the short term - but a runner which is only aware of dart file changes (or actually, js module changes in this case) would likely work well enough to be useful, even if it doesn't always rerun all tests it should (based on css/golden changes etc).

You can use the `*.digests` generated file to get this information (the build_web_compilers builder outputs this for hot restart purposes). It is a map of all transitive js modules for an application to their hash.

**Comment by jakemac53** [comment]
I am going to close this as not planned. The consensus seems to be that this should really be handled at a build system level.

**Comment by DanTup** [comment]
> The consensus seems to be that this should really be handled at a build system level.

Out of interest, what do you mean by "build system level" here? For ex. in VS Code we run `pub run test --reporter -json` (or similar). Would re-running tests on change have to be done by VS Code, or is there another Dart-ecosystem component that could do it (I ask, because the IDE couldn't be very smart about it, whereas in Dart there may be more context to avoid re-running every test on every change).

**Comment by vargavince91** [comment]
The "build system-level" part is also not very clear for me. Could someone, please, give some hints about how the watch mode could be supported by some external package if the Dart team does not want to support this feature within the `test` package?

**Comment by jakemac53** [comment]
What I mean is it requires all the classic components of a build system - dependency tracking, invalidation, and rerunning of invalidated things.

Therefore, it makes sense to integrate this as a part of a build system instead of directly into package:test (implementing a novel build system in package:test isn't likely the right thing to do).

In general though what I mean is wrapping package:test with some other tool that knows how to track changes and re-run tests.

 For instance https://github.com/dart-lang/build/issues/1197

**Comment by DanTup** [comment]
> For instance dart-lang/build#1197

That makes sense to me - thanks! :-)

**Comment by tgrushka** [comment]
Why should a test watcher depend on build_runner and the build system in order to watch files for changes and re-run tests? Almost every other language/framework has the ability to watch tests. Why not Dart? Doesn't make sense. Besides, https://github.com/dart-lang/build/issues/1197 was opened way back in 2018 and still hasn't been addressed.

For others dismayed by coming across this unfortunate decision, here's how I solved it:

```dart

import 'dart:async';
import 'dart:convert';
import 'dart:io';

Future<void> runTests() async {
  final process = await Process.start('dart', ['test']);
  unawaited(process.stdout.transform(utf8.decoder).forEach(stdout.write));
  unawaited(process.stderr.transform(utf8.decoder).forEach(stderr.write));
  await process.exitCode;
}

void main(_) async {
  await runTests();
  final srcWatcher = Directory('lib').watch(recursive: true);
  final testWatcher = Directory('test').watch(recursive: true);
  StreamSubscription? srcSub;
  StreamSubscription? testSub;

  void onData(FileSystemEvent event) async {
    print('Change detected in ${event.path}');
    await runTests();
  }

  srcSub = srcWatcher.listen(onData);
  testSub = testWatcher.listen(onData);

  ProcessSignal.sigint.watch().listen((_) async {
    await srcSub?.cancel();
    await testSub?.cancel();
    exit(0);
  });
}
```
