### ISSUE TITLE
Would like to configure load exceptions to mark a test as skipped instead of failing

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/test#1159]
On our CI infra, every couple of runs a web test will flake due to a failed to load exception. Rather than mark the test as failing, I would like to be able to configure it to mark as skipped - or else provide some hook for us to perform additional actions on a load exception.

https://github.com/flutter/flutter/issues/49435

**Comment by jakemac53** [comment]
I would be concerned about simply marking them as skipped, a bug could easily cause all tests to fail to load and you would get a green CI run which would be bad.

Ideally, we would fix the load exceptions. If it is due to a very high number of tests being ran you could split them up into shards.

Another potential option is doing retries, we already have retry support but I don't know for sure that it works for load exceptions. It is possible that somehow bypasses the retry logic.

**Comment by jakemac53** [comment]
It looks like the retry logic is specific to individual tests within a suite, and if an entire suite fails to load that will not be retried. I think fixing that would probably be the best place to start here.

**Comment by jonahwilliams** [comment]
If we could retry the entire suite, I think that would be preferable. I'm a bit concerned we're getting into some sort of bad state where no other tests would pass, but I don't really know
