### ISSUE TITLE
Headless for Chrome when enabling coverage

### ISSUE THREAD

**Issue by cedx** [dart-lang/test#1171]
When I run browser tests without enabling coverage, Chrome runs in headless mode.
But when I enable coverage, Chrome seems to run in GUI mode: this breaks tests in CI environments (GitHub Actions, Travis CI, ...) where we don't have a GUI.

**Comment by grouma** [comment]
Coverage runs imply `debug` mode. We have this conditional which ties it to the headless feature:
https://github.com/dart-lang/test/blob/26ba571a2699e69fd5f23272e91ac7fea45733a8/pkgs/test/lib/src/runner/browser/chrome.dart#L61

Since we can explicitly configure the headless feature I don't see any concern in updating that conditional. I'll happily review a PR.
