### ISSUE TITLE
Add succeed()

### ISSUE THREAD

**Issue by feinstein** [dart-lang/test#1218]
Test have a `fail()` function that interrupts the current test with a failure, but I can't find a `succeed()` or `pass()`, that would do the equivalent, but making the test succeed.

**Comment by natebosch** [comment]
Usually the solution for this pattern is `return;`.

Adding a `succeed()` that interrupts further execution and marks the test as successful won't be easy to do - the the simple case it's effectively `return` but with an exception. In more complex cases we'd have to figure out how to handle things.

It's not clear to me what we would do if a `succeed()` were thrown asynchronously and received after a failure. Or what we would do if a `succeed()` is thrown and then an error surfaces asynchronously.

We don't have any ability to "interrupt" code that is running, or waiting to run on the event loop, and I'd strongly prefer not to try to hook deeply into the event loop and microtask queue to stop execution of code that would otherwise run.

Do you have a particular case where `return;` is not feasible?

**Comment by feinstein** [comment]
Not a particalar case, just used with JUnit, I understand this won't be simple so I will close this.

PS: I need some help with some asynchronous tests, but I can't find anything online nor anyone that I know of that can help me, where could I ask for some directions? Thanks.
