### ISSUE TITLE
Printing to stdout when using runner should be configurable

### ISSUE THREAD

**Issue by fodil-a** [dart-lang/test#1228]
Hi,

**When**: I use Runner.run(), 
**I want**: Runner reporters to print into a custom output stream instead of stdout
**Current behavior**: it prints to stdout all the time

**Comment by fodil-a** [comment]
I already pinpointed this issue:

https://github.com/dart-lang/test/blob/7514d98b420f15e577e52606bd85e79ffc0428cd/pkgs/test_core/lib/src/runner.dart#L91-L97

I believe that this behavior is heavily used.
So I think that we should have a different factory, which would take an IOSink as the wanted outputStream.
This outputStream won't be owned by Runner, so Runner won't have to manage it.

**Comment by natebosch** [comment]
It looks like for your specific use case you should be able to use `--file-reporter` argument to ask for the json output to a file while getting the default reporter on stdout.

If you specifically need to have _no_ reporter writing to stdout I think we could create a no-op reporter. Please let us know if that's the case, otherwise I'll close this for now and focus on the immediate issue of interrupting the json output from #1226
