### ISSUE TITLE
How to get the value of  --shard-index within test code?

### ISSUE THREAD

**Issue by peter-chung-sensestar** [dart-lang/test#1426]
tried something like this with null returned 

```dart
import 'package:test/test.dart';
import 'package:test_core/src/runner/configuration.dart';

void main() {
  setUp(() {
      print("shardIndex = ${Configuration.current.shardIndex}");
  });
}
```

**Comment by jakemac53** [comment]
We don't expose it - this should not be visible to the test because tests should run the same regardless of which shard they are in. Note that the current configuration object is also considered a private thing, and it can and will have breaking changes without a breaking change release.

What is it you would like to achieve with the shard index?

**Comment by peter-chung-sensestar** [comment]
@jakemac53 Thanks. I think my problem can be solved by env vars.
