### ISSUE TITLE
Reflected <List> param impossible to compare

### ISSUE THREAD

**Issue by pro100svitlo** [dart-lang/test#1515]
```dart
class Temp {
  final List<String> list;

  Temp(this.list);
}
```

```dart
void main(){
  test('validate proper list type', () {
    final mirror = reflectClass(Temp);
    final expected = <String>[].runtimeType;
    final actual = mirror.declarations.values
        .whereType<VariableMirror>()
        .first
        .type
        .reflectedType;
    expect(actual, equals(expected));
  }); 

}
```

Throws error which doesn't make much sense 🤔 
```dart
package:test_api                            expect
test/test.dart 116:7  main.<fn>.<fn>

Expected: Type:<List<String>>
Actual: Type:<List<String>>
```
-------

`which dart` ->
`Dart SDK version: 2.12.3 (stable) (Wed Apr 14 11:02:39 2021 +0200) on "macos_x64"`

**Comment by jakemac53** [comment]
The `equals` method only special cases a couple things (like collections), otherwise it just falls back on regular object equality.

It looks like runtime type objects (with generics at least) do not implement equality in the way you might expect, it is likely just instance equality? In some cases these are canonicalized but I don't think that is a requirement. My guess is that specifically using mirrors gives you back non-canonicalized types here?

You could file an issue on the language but this is not likely something that can change.
