### ISSUE TITLE
TestFailure doesn't implement Exception?

### ISSUE THREAD

**Issue by Hixie** [dart-lang/test#1601]
I tried to enable the `only_throw_errors` lint, and ran into a problem where code that manually throws TestFailures is flagged because that class doesn't implement Error or Exception.

**Comment by natebosch** [comment]
This changed turned out to break some flutter tests since there is code that changes the output about a failure depending on whether the thrown object implements `Exception`.

https://github.com/natebosch/flutter/blob/f0c9a32242511a4e089dcc0fc12be7a3dcd05714/packages/flutter/lib/src/foundation/assertions.dart#L639-L643

I'll go with updating the hardcoded output expectations - I don't think the old `TestFailure object` description was more useful than `TestFailure` in these messages. https://github.com/flutter/flutter/pull/94172

**Comment by Hixie** [comment]
Awesome, thanks!
