### ISSUE TITLE
expectLater waits indefinitely without timing out

### ISSUE THREAD

**Issue by crtl** [dart-lang/test#1716]
Documentation for timeouts states:
> By default, tests will time out after 30 seconds of inactivity. The timeout applies to deadlocks or cases where the test stops making progress, it does not ensure that an overall test case or test suite completes within any set time.

But using `expectLater` with `emits` matcher for streams the test will run indefinitely when no events are emitted.

Test case:
```dart
@Timeout(Duration(seconds: 30)) // This also has no effect
void main() {
 test("expectLater wont timeout", () async {
    final controller = StreamController();

    await expectLater(controller.stream, emits(1));
  });
}
```

Command to run the test is (via android studio):
```
flutter.bat --no-color test --machine --start-paused test\unit-tests\path\to\test.dart
```

**Comment by jakemac53** [comment]
This test does time out as expected when ran via `dart test`. I believe this is likely an issue with `flutter test`. They have their own test platform, and it likely isn't supporting the timeouts appropriately, or possibly they made a conscious choice to not support timeouts (I seem to remember this coming up recently...).

I can't transfer issues to the flutter repo (since its a different org), so I will close this one and you will need to file a new one over there (https://github.com/flutter/flutter).

**Comment by crtl** [comment]
@jakemac53 Thanks for the reply, I will do so.
