### ISSUE TITLE
Hooks for running at the start and end of all the tests in test folder

### ISSUE THREAD

**Issue by kalluriramkumar** [dart-lang/test#1770]
When there are multiple test files, is there a way to run something at the start of all tests and then again at the end of all tests?

Like how the `setUpAll` runs before all tests in a test file, similarly when there multiple test files ( `a_test.dart` and `b_test.dart` ) then run at the beginning and at the end of all the tests in the `test` folder. For instance, a typical use case could be initializing an in-memory database at the start of all tests and clear it at the end of the tests.

Something very similar to `@beforeSuite` in [testNG](https://testng.org/doc/documentation-main.html#annotations)

**Comment by jakemac53** [comment]
There is no hook for this because each test suite is run in complete isolation from all other tests (in its own isolate, iframe, etc) - so you wouldn't be able to share an in memory object among all test suites.

The best way to accomplish something like this would be to have a single top level test file, which has the `setUpAll` etc, and then it import all the other "test" files (but they wouldn't end in `_test.dart`). It would invoke a helper function in each, passing in the initialized object.

**Comment by jakemac53** [comment]
Note that you could also probably code generate that entrypoint test file, to ensure it always imports all the other files, which is the main risk of this approach.
