### ISSUE TITLE
`dart test` recommends a command that doesn't work on Windows

### ISSUE THREAD

**Issue by timsneath** [dart-lang/test#1798]
Consider the case where a test fails, when running `dart test`. 

Dart helpfully presents a command to run to replay the failed test. For example:

```
[C:\src\win32\tool\generator] dart test test\utils_test.dart
00:02 +0 -1: iidFromTypeIdentifier [E]
  Expected: '{03362E33-E413-5F29-97D0-48A4780935F9}'
    Actual: '{03362e33-e413-5f29-0000-000000000097}'
     Which: is different.
            Expected: {03362E33-E413-5 ...
              Actual: {03362e33-e413-5 ...
                            ^
             Differ at offset 6

  package:test_api            expect
  test\utils_test.dart 567:5  main.<fn>


To run this test again: c:\src\flutter\bin\cache\dart-sdk\bin\dart.exe test test\utils_test.dart -p vm --plain-name 'iidFromTypeIdentifier'
00:02 +0 -1: Some tests failed.

Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.
```

However, on Windows, this command has unnecessary quotes, which causes it to fail if you paste it back into the shell:
```
[C:\src\win32\tool\generator] dart test test\utils_test.dart -p vm --plain-name 'iidFromTypeIdentifier' 
No tests ran.
No tests match "'iidFromTypeIdentifier'".

[C:\src\win32\tool\generator]
```

Instead, on Windows, you need to remove the quotes, for example:
```
[C:\src\win32\tool\generator] dart test test\utils_test.dart -p vm --plain-name iidFromTypeIdentifier
00:02 +1: All tests passed!
```

### Repro Environment
```
[C:\src\win32\tool\generator] dart --version
Dart SDK version: 2.19.0-416.0.dev (dev) (Mon Nov 21 18:50:19 2022 -0800) on "windows_x64"
```

**Comment by jakemac53** [comment]
This is actually pretty complicated because test names can have quotes in them, as well as spaces. Combine that with the bash shell in VsCode on windows and things get quite challenging actually 😮‍💨 .

Today when I try the given output in VsCode, in the bash console there, it seems to expect forward slashes for paths and treats the back slashes as escapes. Replace all the back slashes with forward slashes and it works (the quotes are fine).

If I open up a command prompt, the back slashes are all fine but the test name gets mangled by the single quotes, swapping those to double quotes works.

This will definitely take a lot of investigation and trial/error to fix.

**Comment by jakemac53** [comment]
One proposed "fix" could be this:

- Swap to using double quotes on windows, and don't bother trying to do fancy escaping other than of nested double quotes in the test names. We use single quotes today because it means we don't have to do escaping on linux, but clearly on windows it is doing something totally different (or at least, the default command prompt).
- Keep emitting back slashes, that is the default on windows. Unless somebody has a suggestion for how to detect if the current console expects forward slashes. This just won't work in the bash shell in VsCode, but users can use powershell there instead easily.

**Comment by jakemac53** [comment]
cc @natebosch

**Comment by natebosch** [comment]
> * Swap to using double quotes on windows, and don't bother trying to do fancy escaping other than of nested double quotes in the test names.

+1

> * so we could just always force it to use forward slashes?

I guess that should be OK. Would we use `path.posix` to force it?

> * We would have to convert the `Platform.resolvedExecutable` path to forward slashes

I wonder if we need to be using `resolvedExecutable` at all here. Since it's aimed for someone to copy/paste, I think `executable` should always match how they got there.

**Comment by jakemac53** [comment]
> I wonder if we need to be using `resolvedExecutable` at all here. Since it's aimed for someone to copy/paste, I think `executable` should always match how they got there.

It is actually generally a bit confusing - in the command prompt it does just output `dart`, where in VsCode bash windows it outputs the full path (with backslashes). Maybe bash is resolving it, and we are just using `Platform.executable`. Will have to look.

**Comment by natebosch** [comment]
We are using `Platform.executable`.

https://github.com/dart-lang/test/blob/7cfd49e9e8ac8dde507e6982c8f111fa51c6e664/pkgs/test_core/lib/src/runner/reporter/compact.dart#L228

How are you running the tests? I can imagine if you run them with VSCode instead of running `dart test` yourself then it might be showing you the path that VSCode used to execute it.

**Comment by jakemac53** [comment]
I am running `dart test` but inside a bash console in VsCode. Not sure exactly why it gets a fully resolved path.

**Comment by jakemac53** [comment]
Ultimately I think we should just swap to use double quotes on windows, fwiw

**Comment by natebosch** [comment]
Yeah, I think for quoting issue it's clear we should switch to surrounding with double quotes, and escaping `"` as `"""` within the string.

**Comment by natebosch** [comment]
Hmm, Using `"""` as the escape will cause new problems trying to copy this code in bash in VsCode. Its the best choice for the windows shell as I understand it.
