### ISSUE TITLE
Tests: expect: It is not assert. A failed expect should not stop execution

### ISSUE THREAD

**Issue by WorikQCI** [dart-lang/test#1981]
I hope this is the correct place to raise this issue.  I raised it in the wrong place earlier.

It is a general issue about testing.

**Is your feature request related to a problem? Please describe.**
When I build a unit test to test a function I often want to test on a set on inputs.

Some will fail, some will succeed.

I am testing a function so each call to it is independent

So if an `expect` fails I wish the `expect` calls after it to still be executed.  Otherwise I am wasting time.

As it stands the `expect` call is entirely superfluous as there is already an `assert` that does basically the same thing.

```
  test("except==assert", () {
    print("true, true");
    expect(true, true);
    print("false, false");
    expect(false, false);
    print("false, true");
    expect(false, true);
    print("false, false");
    expect(false, false);
    print("true, false");
    expect(true, false);
  });
```

Outputs:
```
00:00 ESC[32m+0ESC[0mESC[33m ~1ESC[0m: except==assertESC[0m

true, true

false, false

false, true

00:00 ESC[32m+0ESC[0mESC[33m ~1ESC[0mESC[31m -1ESC[0m: except==assert ESC[1mESC[31m[E]ESC[0mESC[0m

  Expected: <true>
    Actual: <false>
  

  package:test_api/src/expect/expect.dart 134:31     fail
  package:test_api/src/expect/expect.dart 129:3      _expect
  package:test_api/src/expect/expect.dart 46:3       expect
  test/issue_demo_test.dart 27:5                     main.<fn>
  package:test_api/src/backend/declarer.dart 215:19  Declarer.test.<fn>.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/declarer.dart 213:7   Declarer.test.<fn>
  ===== asynchronous gap ===========================
  package:test_api/src/backend/invoker.dart 257:7    Invoker._waitForOutstandingCallbacks.<fn>
  

00:00 ESC[32m+0ESC[0mESC[33m ~1ESC[0mESC[31m -1ESC[0m: ESC[31mSome tests failed.ESC[0m

```

It detected the first: `    expect(false, true);` but failed to detect the following: `expect(true, false);` 

* Dart SDK Version (`dart --version`)

`Dart SDK version: 2.19.5 (stable) (Mon Mar 20 17:09:37 2023 +0000) on "macos_arm64"`

* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)

Command line testing on MacOS

**Comment by lrhn** [comment]
Moved to test package repo. So now it is the right place!

You really want two different kind of checks.
Some checks are fatal, and prevent further testing, because you didn't get the value you need to do the further tests.
Other checks are not fatal, because you're doing multiple independent checks in the same test.

My impression is that you're expected to split independent checks into independent tests, which would allow them to succeed or fail independently.

**Comment by WorikQCI** [comment]
"Some checks are fatal"  For which there is `assert`.  A perfectly good function.

"My impression is that you're expected to split independent checks into independent tests, which would allow them to succeed or fail independently."  That is exponentially more work, and unnecessary.

**Comment by jakemac53** [comment]
While I think there is a case to be made for something like `expect` which doesn't throw, it is simply not feasible to change how `expect` works even if we agreed that the behavior you want is the correct behavior. There are millions of existing tests in the world that it isn't worth breaking.

We could consider adding a new function or something, but the `expect` is about to be essentially deprecated anyways as we move to the `checks` package. So I don't see us doing any further feature work there without a really significant reason.

It is possible that the new `checks` package could consider a mechanism for this though, cc @natebosch. I am not sure how well the new test hooks we are adding could fundamentally support it or not, but that at least would be worth doing I think so that new packages can be released by the community with such support.

In general, we are working on supporting custom matcher/expectation packages, and I expect the community to start releasing some once that is more stable and available from `flutter` (today it isn't because they pin deps and rolling the new versions is hard, but we are working on it). 

> "Some checks are fatal" For which there is `assert`. A perfectly good function.

I explained in https://github.com/Dart-Code/Dart-Code/issues/4470#issuecomment-1489383518 why these aren't the same. Please read that comment again.

> "My impression is that you're expected to split independent checks into independent tests, which would allow them to succeed or fail independently." That is exponentially more work, and unnecessary.

It is not exponentially more work, it's linear, and we have millions of tests out there without lots of people filing issues like this.

**Comment by natebosch** [comment]
> It is possible that the new `checks` package could consider a mechanism for this though, cc @natebosch. I am not sure how well the new test hooks we are adding could fundamentally support it or not

Yes, this can be implemented with `addTearDown`. 

https://github.com/dart-lang/test/pull/1898 has an implementation. Naming is one of the sticking points, since we don't want to reuse the name `expect` since it makes the migration harder, but `expectThat` is clunky next to `check` and `assume`.

> That is exponentially more work, and unnecessary.

Many independent tests with one reason to fail is the style of testing encouraged within Google, and the style we will optimize for within our testing packages. We consider it a best practice to have a mismatch associated with a narrow test name so that the failure output gives enough context to start an investigation.

Feel free to add a :+1: on the linked PR to express support for a mechanism to collect multiple failures per test case.

I'm going to close this for now, since we're already separately considering this feature in `checks`, and have no plans to backport it to `matcher`.
