### ISSUE TITLE
Make `test_on` exit with 0 on non-supported platforms

### ISSUE THREAD

**Issue by Levi-Lesches** [dart-lang/test#2277]
I am using `test_on: windows` to prevent Windows-specific FFI code from running on GitHub Actions's Ubuntu runners. Unfortunately, this prints an error and more importantly, fails the CI, which does run other Linux-related tasks. 

By specifying `test_on`, I am saying that these tests will cause errors that aren't relevant and I wish to silence the whole process. Failing the tests anyway goes against this and isn't helpful in this case. 

[This](https://github.com/dart-lang/test/blob/569c6eb6eb8ceeefd188e1422e39796e15062d47/pkgs/test_core/lib/src/runner.dart#L111) function checks for unsupported platforms but only logs to the console and doesn't affect the return value or whether a `NoTestsFoundException` is thrown. Maybe that can be changed in this specific case?

In my case, I'm in a mono-repo of a federated plugin managed by `package:melos`, so as a workaround I configured melos to ignore the Windows tests and extracted them to a separate step, which I then only run on `windows-latest`.

**Comment by jakemac53** [comment]
Just to clarify, this is exiting with a non-zero exit code because no tests are actually running? That is working as intended if so, and that is important default behavior because running no tests is almost always an error in configuration.

Configuring the job to only run on windows is the correct solution and should leave you in a better state overall (not running meaningless CI jobs).

We could consider configuration (flag + dart_test.yaml) which allows you to toggle this default behavior, but I am not sure how much value there really is in that? cc @natebosch

**Comment by natebosch** [comment]
I do feel that the current behavior is the right default since the situation is much more likely caused by an inadvertent  than intentional configuration change that skips all tests.

I don't think it is worth adding a configuration option or CLI flag since it's so niche - it seems like this is more a limitation of the generated CI config than a limitation of CI in general.

I think that not running that `dart test` command at all on that platform is the right approach.

If that is infeasible another (admittedly hacky) option is to add a small `allow_all_skipped_test.dart` file with something like.

```dart
import 'package:test/test.dart';

void main() {
  test('empty test case to allow skipping all other tests', () {}));
}
```
