### ISSUE TITLE
Tests with multiline descriptions and string expressions are not runnable from CodeLens links

### ISSUE THREAD

**Issue by MauriMiguez** [dart-lang/test#2412]
When running a test CodeLens links that happens to have a multiline description as well as using the string expression with types recommendation it throws an error (No tests match regular expression).

Running from the CodeLens links:
![image](https://github.com/user-attachments/assets/e19594c1-1ca8-432b-b635-8e5d99774e1f)

Error:
![image](https://github.com/user-attachments/assets/602ee21e-912f-4128-a155-aa81e656292b)

Platform: Apple M1
OS: Sequoia 15.0.1
Dart SDK Version: 3.5.3
Version of `package:test` : 1.25.8

Reproduction example:
```
class MyClass {
  void myMethod() {}
}

void main() {
  test(
      '$MyClass very looooooooooooooooooooooooooooooong test description '
      'my method returns normally', () {
    final myClass = MyClass();

    expect(myClass.myMethod, returnsNormally);
  });
}
```

**Comment by jakemac53** [comment]
Yes, any interpolations do break the integration, because it just does a basic regex or something over the parsed string.

It is unfortunate to be sure, but we added a feature to fix this a while ago, which is to run tests by line/column. So, CodeLens could use that feature instead of the "run by name" feature, which has a lot of other issues beyond just this one.
