### ISSUE TITLE
Add command line option for changing default timeout

### ISSUE THREAD

**Issue by danschultz** [dart-lang/test#279]
Would be nice to have a command line option to specify the global timeout.

**Comment by whesse** [comment]
A number of issues with the buildbot have been caused by not being able to increase this internal timeout.  This should be a higher priority.  We are disabling debug runs because of this.

@sgjesse @ricowind

**Comment by zoechi** [comment]
I think this is covered by #63 and #46

**Comment by whesse** [comment]
In our case, a command-line argument is much better than a file.  The package directory might be shared with other configurations which are running with different parameters, or it might be read-only.  Even if the configuration file can be specified on the command line, then we need to create a file somewhere, and then specify its path, rather than just putting the option on the command line.  Perhaps the command line could accept the JSON or YAML that would be in the configuration file.

**Comment by nex3** [comment]
I agree that this should be done soon to get the bots happy.
