### ISSUE TITLE
default pub-serve to 8080 if no value supplied

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/test#286]
I find myself typing `--pub-serve=8080` a lot. It would be nice if you could just do `--pub-serve` and it would default to 8080 since that is the pub serve default.

**Comment by nex3** [comment]
The `args` package doesn't support options that may or may not take an argument. And for good reason: it would make `cmd --arg value` amiguous between `cmd --arg=value` and `cmd --arg -- value`. You could theoretically make it only work with an explicit `=`, but that would be weirdly inconsistent with other options, and since the option already exists it would be backwards-incompatible.

Also, it's not even clear that 8080 is the right default. If a `web/` directory exists (which is presumably reasonably common), `pub serve` will default to serving `test/` on port 8081.
