### ISSUE TITLE
Improve performance of running many test files

### ISSUE THREAD

**Issue by lassedamgaard** [dart-lang/test#318]
In https://github.com/dart-lang/test/issues/317 I noticed that if you have a largish number of test files, it is much faster to generate a single entry point that imports all the tests and run their main methods instead of having the test runner launch each file individually.

In my case running ~800 tests spread across ~80 files produces these results:
```
zeta:foobar lasse$ pub run test --version
0.12.4+3
zeta:foobar lasse$ pub run test test/test_*.dart --platform content-shell --concurrency 1 --reporter compact
02:55 +805: All tests passed!                                                                      
zeta:foobar lasse$ dart scripts/gen-test-runner.dart test
Generating "run_tests.dart" in /Users/lasse/foobar/test
zeta:foobar lasse$ pub run test test/run_tests.dart --platform content-shell --concurrency 1 --reporter compact
01:24 +805: All tests passed!                                                                      
```

The generated test runner ```run_tests.dart``` just imports all the test files and launches them:

```dart
import 'test_bar.dart' as test_bar;
import 'test_foo.dart' as test_foo;

main() {
  test_bar.main();
  test_foo.main();
}
```

**Comment by nex3** [comment]
This is, more or less, intended. We spawn a new isolate for every test suite, which buys us several things: it means that test suites run independently and can't interfere with one another; it means that we can run multiple suites in parallel; and it helps us isolate load failures so that a syntax error in one suite doesn't take down the whole test run. Unfortunately it also has downsides, since spawning a new isolate can be quite slow even if it shares a lot of code with existing isolates, but we do it this way because we believe those downsides are outweighed.

It's also worth noting that your comparison isn't really accurate, since you're passing `--concurrency 1` in both cases. This means that any performance gain you get from parallelism—one of the reasons we use separate isolates in the first place—is lost. It's probably still going to be slower on the whole, but not as much as your example makes it out to be.

**Comment by lassedamgaard** [comment]
Fair enough. 

For the record running with concurrency 4 only gives a ~8% increase in speed (2:33) compared with the ~51% increase from running everything as one file. So this might be a valid feature request. For now, I'm happy with my batch-file generation script and I guess others can just do that (10 lines of code) if they want.
