### ISSUE TITLE
A skipped group should increase the number of skipped tests by the number of tests in the group 

### ISSUE THREAD

**Issue by zoechi** [dart-lang/test#331]
Currently when a group with an arbitrary number of tests is skipped the reporter (print output) increases the number of skipped tests only by 1 but it should increase by the number of all tests contained in the skipped group.

**Comment by nex3** [comment]
This is intentional. There are a couple reasons we do this; first, it means that if a user has written live code in their `group()`, it's skipped as expected, since we don't have to run the group body to get the number of tests. This isn't great style, but people do do it. Second, it means that if you provide a skip reason (and you should!) it doesn't propagate down to all the tests in the group and print over and over; we're able to just print it for the group itself and nowhere else. There's not a good way to do in the reporter paradigm and *also* list all the tests.

**Comment by zoechi** [comment]
This was expected but worth a try.
I didn't mean to list all titles of skipped tests, I just wanted the number of skipped tests increased by the real number.

**Comment by nex3** [comment]
Because of the way the reporter API works (an API we want to keep simple since it'll be a plugin surface), there's no real distinction between test names and the test count. And we'd still have to run the group block to get either one.
