### ISSUE TITLE
Allow customizing a test-runner run, by giving input to the test runner

### ISSUE THREAD

**Issue by whesse** [dart-lang/test#352]
There seems to be no way of skipping tests or expecting failures, from the test runner command line.  Could we pass in a JSON object, that would include custom timeouts, expectations, and skip markers for running individual tests?

There is currently no way to mark individual tests as failing, or to be skipped, except by modifying the test source code, as far as I know.  This is especially a problem when individual tests in a file have different statuses, that depend on the platform or debug mode that we are running in.

Unless status files, with all the complexity of test.py's status files are added, then this or some other solution seem to be necessary for running package:test tests in a automated framework, that tests scores of different configurations, and will have to note failures on specific configurations.

Alternately, we could provide an analyzable output for each test, and handle failures there.  But that doesn't address skipping tests or giving them longer timeouts.

**Comment by nex3** [comment]
I'd really like to avoid doing this, because I want to avoid people re-creating non-standard external status files. This was a major pain point with the old system, and including all the test configuration in the test files themselves is an important design goal of the test runner. It makes it vastly easier to reproduce test servers' behavior locally, and helps ensure that tests are run with consistent configuration on each platform.

Luckily, what you want to do is already largely possible within the test files, and there are plans in place to cover the rest of the needs you describe. Right now, the `@OnPlatform` annotation and the `onPlatform` parameters to `test()` and `group()` allow you to specify [platform-specific configuration](https://github.com/dart-lang/test#platform-specific-configuration). Once #16 is in place, you'll also be able to give tests customizable tags, and filter/configure based on those tags from the command-line.
