### ISSUE TITLE
JSON reporter: Add location of test call in 'testStart` event

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/test#380]
Perhaps by adding such info to the `Test` and `Group` objects?

https://github.com/dart-lang/test/blob/master/json_reporter.md#other-classes

**Comment by nex3** [comment]
Can you provide more detail here? Is this just for the JSON reporter? Does the reporter just need to include the test's filename? Does it need to include platform information as well?

**Comment by kevmoo** [comment]
@stevemessick Can you comment here?

**Comment by stevemessick** [comment]
Details in https://github.com/dart-lang/test/issues/376

**Comment by kevmoo** [comment]
@stevemessick Could you define your requests in terms of how you'd like the JSON output to change?

https://github.com/dart-lang/test/blob/master/json_reporter.md#other-classes

I could imagine adding some sort of source location (file + line/column offset) to the Test and Group objects.

**Comment by alexander-doroshko** [comment]
@nex3 @stevemessick 
Integration with package:test is almost done in IntelliJ IDEA / WebStorm. It is possible to run a single test, single group, all tests in a file and (I guess the most common use case) all tests in a package. As a result user is getting a nice test results tree:
![image](https://cloud.githubusercontent.com/assets/4499789/12554033/af06d3b8-c38b-11e5-80a4-b34a0812e86a.png)

I think there's only one missing major feature: user is not able to jump to test or group source from the test result tree. IDE needs a hint from package:test that would allow to locate it. The answers to @nex3 questions are the following:
- Yes, we need location info only when tests are run with JSON reporter (`-r json` option).
- We'd be happy with relative path from the Dart package root to the *.dart file where the test/group is declared. Absolute paths would be fine as well if you find them better. By test/group declaration I mean `test(...)` / `group(...)` function calls in user code.
- No, we do not need platform information.

As for the possible implementation, I like the idea of @kevmoo: add `String filePath` field to the [Test](https://github.com/dart-lang/test/blob/master/json_reporter.md#test) and [Group](https://github.com/dart-lang/test/blob/master/json_reporter.md#group) classes.

IDE can parse files and look for `test(...)` / `group(...)` function calls itself. But some cases are difficult for the IDE (e.g. when test name is not a string literal, but a variable initialized somewhere else). So as a bonus we'd be happy with additional `int line` and `int column` fields of `Test` and `Group` classes as well. Note that `offset` instead `line` and `column` won't work because of IDE-specific line breaks normalization.

Thanks for taking a look!

**Comment by nex3** [comment]
There are two ways we could go here, the easy way and the hard way. The easy way would be to just provide the path to the suite itself, without line and column information. We already have this information, it's just not exposed in the JSON reporter at the moment. However, it's inexact; it's possible for a test to be declared in a file the suite imports, or otherwise dynamically.

The hard way would get closer to your ideal output. We'd have to capture a stack trace at the point a test is declared and pipe that all the way through to the reporter. This is doable, but it will take more time and consequently be further down on the priority list (although certainly still a priority for Q1).

**Comment by alexander-doroshko** [comment]
Thanks for info! I'm happy with quick and inexact solution for now and waiting more for the ideal one.
