### ISSUE TITLE
Add a matcher for an unwanted failure

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#395]
This would allow users to mark a test as failing, while ensuring that the failure keeps occurring and continues to be in the expected form.

The signature should be something like `Matcher fails(matcher)`, where the argument is applied to the first error that's thrown. This would differ from `throwsA` in the following ways:
- It would print a message indicating that the failure occurred, to remind the test author to fix it in the future.
- If it's run against a function, it would run the function in an error zone and capture any out-of-band errors it throws as well.
- It would use the internal `waitForOutstandingCallbacks()` infrastructure to block the test's completion until the function completed as a test case would.

This would allow users to effectively move an entire test case into an `expect()` call for this matcher. For example:

``` dart
test("failing test", () {
  expect(() async {
    // original test body
  }, fails(isStateError));
});
```

This matcher would need to exist in `test` because of its asynchrony and interaction with `test`'s internal infrastructure.

**Comment by jakemac53** [comment]
:+1: 

Curious, if I had an `expect(1, equals(2));` call inside that block, what would my matcher need to look like?

**Comment by nex3** [comment]
`throwsA(new isInstanceOf<TestFailure>())`.

**Comment by grouma** [comment]
throwsA should handle this use case.

**Comment by mattalbr** [comment]
I know this is a very old, but I don't believe `throwsA(isInstanceOf<TestFailure>())` handles this case generically.

The test I'm trying to write is as follows:

I have a Bloc which has an event handler that under particular circumstances throws (intentionally). I would like to recreate those circumstances and document them via a unit test. The problem is that the error that gets thrown is thrown by the event handler, which is just a stream subscriber that callers have no access to. So, there's no way to wrap any particular call in an `expect(..., throwsA)` because the exception always ends up in the CAUGHT BY FLUTTER TEST FRAMEWORK. Nor is it possible to call the event handler directly without the event stream, because the handlers depend on an `Emitter` which has no public implementation. I could create my own, but that's way overkill for this (and either way demonstrates that this expect(..., throwsA) isn't sufficient).

So I tried to write the test all kinds of ways -- FlutterError.onError didn't work for me, nor did runZonedGuarded. In the end I gave up and was hoping to find some kind of failing_test so at least I could assert that this test fails. But following the recipe here, the test still fails.

I haven't tested this exact code, but I think minimally reproducible could should be something like:
```
import 'package:bloc/bloc.dart';
import 'package:equatable/equatable.dart';
import 'package:flutter_test/flutter_test.dart';

class Event extends Equatable {
  const Event();

  @override
  List<Object?> get props => [];
}

class State extends Equatable {
  const State();

  @override
  List<Object?> get props => [];
}

class MyException implements Exception {
  final String msg;
  const MyException(this.msg);

  @override
  String toString() => 'MyException: $msg';
}

class FailingBloc extends Bloc<Event, State> {
  FailingBloc() : super(State()) {
    on<Event>(alwaysFails);
  }

  void alwaysFails(Event event, Emitter<State> emit) {
    throw MyException("whoopsie");
  }
}

void main() {
  // This test fails on two counts.
  // 1: the throwsA doesn't match
  // 2: the Flutter Test Framework receives MyException and fails.
  test('Fails, () {
    expect(() async {
      final bloc = FailingBloc();
      bloc.add(Event());
      // There's probably a better way, but we await this future
      // to spin the event loop to allow FailingBloc to handle the event.
      await Future.delayed(const Duration(seconds: 1));
    }, throwsA(anyOf(isA<MyException>(), isA<TestFailure>())));
  });
}
```

I realize this test is very flutter specific, but I believe it demonstrates the generic case of an exception thrown into the ether by a stream subscriber, which is then unable to be caught by a test expectation.
