### ISSUE TITLE
Add a zoneThrows matcher

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#418]
Sometimes asynchronous code fails in ways that aren't neatly exposed by a stream or a future, and sometimes that code needs to be tested. We should expose a matcher in the style of `throwsA()` to make this easy. It should match a callback by running that callback in a zone and asserting that the zone produces a (single?) error that matches the inner matcher.

**Comment by natebosch** [comment]
cc @jakemac53 - I'm curious what your thoughts are on this given some of our recent discussions about unhandled async error stuff.

My gut reaction here is that an unhandled async error is very likely to be a bug, and not something you'd want to assert does happen. In the rare edge cases where you do want to assert that an unhandled async error is thrown, it's probably OK to need to write this utility yourself. Putting it in a shared package might appear to encourage it.

**Comment by jakemac53** [comment]
I don't think we would need to worry to much about encouraging bad behavior here. There are legitimate use cases, which we might as well support.

The main question from my perspective would be whether it should match exactly one error or multiple.

**Comment by jakemac53** [comment]
I think also there is a broader question of whether it provides enough value to be worth implementing/supporting 🤷‍♂ . Given that this issue is quite old with nobody chiming in it probably isn't worth doing.

**Comment by natebosch** [comment]
Here is a reference implementation:

https://github.com/dart-lang/async/blob/c1e7227ca669822bc84cd2d6c353c8cde0e8c68b/test/utils.dart#L25

FWIW As soon as we roll the next breaking release of `async` we'll drop that test utility. I traced it down and this is only necessary to test `DelegatingStreamTransformer.typed` which we want to remove. I think I'll close this issue as not enough use case since we don't know of any other place we'd want it.
