### ISSUE TITLE
How to run unit tests in parallel mode?

### ISSUE THREAD

**Issue by ashokdudhade** [dart-lang/test#439]
I have more than 1000 unit tests, to run all tests it takes more than 10 minutes. To minimize this execution time I tried using "concurrency" mode but its not improving, Am I missing something?
```pub run test  test/unit -p vm -p content-shell --concurrency=6```

**Comment by kevmoo** [comment]
@ashokdudhade how many cores do you have on your machine?

The default is to use `coreCount/2`. If you push much more than that, you're likely to hit a lot of contention – pushing concurrency too far might actually make things slower.

**Comment by nex3** [comment]
And if you do have multiple cores, manually setting `--concurrency` may not do anything meaningfully different than the default, since the default already runs concurrently. You can try passing `--concurrency=1` to get an idea of how long a fully serial run takes.

Unfortunately, concurrency isn't a magic bullet. If your tests are slow, running them in parallel on the same machine can only do so much. I'm going to close this out because there's not really anything we can do in `test` to address the issue.

**Comment by ashokdudhade** [comment]
@kevmoo I have 8 cores on my machine. 
Any suggestions on improving test execution performance?
