### ISSUE TITLE
Support "retry" for content-shell

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/test#449]
On travis, we frequently have issues starting up content-shell, which leads to all content-shell tests failing.

https://travis-ci.org/dart-lang/angular2/jobs/151296901

In cases where content-shell fails to run, it'd be nice to have some retry logic.

**Comment by nex3** [comment]
What behavior are you concretely requesting here?

**Comment by kevmoo** [comment]
If content-shell exits before the first test is run, try to restart it n times (3).

Maybe with a pause between. Before "really" failing.

Seeing a lot of flakes here.

**Comment by vpigrad** [comment]
It would be better to fix the problem rather than the symptom.  It's very frustrating to have such an unreliable test framework.  Every single night we run our ~4,300 tests, we have several fail at random.  It's getting impossible for me to pressure our developers into fixing tests since they've lost faith in the test framework.

**Comment by kevmoo** [comment]
@vpigrad is your problem with content-shell or pkg/test in general?

Keep in mind: content-shell is a bit of a hack – and has always been, even from the Chrome team's perspective.

We're tracking [headless chrome](https://twitter.com/samccone/status/739166801427210240) work and hope to have a solution around that at some point.

**Comment by vpigrad** [comment]
content-shell generally works, but keep in mind when you have thousands of tests, even a 1% failure rate is a major problem.

**Comment by nex3** [comment]
I strongly suggest running Dartium rather than content shell for continuous integration builds. As Kevin points out, content shell's developers don't intend to give it strong reliability guarantees, so you're always going to have some frustration when including it in your core test loop.

@kevmoo This point also applies to Angular. They should probably be running their Travis tests on Dartium rather than content shell, especially if flaky failures are becoming a real problem.

**Comment by kevmoo** [comment]
@vpigrad FYI: I've found with content-shell on travis a couple of helpful things.

```yaml
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
```

Recommended by Travis for using xvfb.

Also: run tests with `pub run test -p content-shell -j 1` – seems that xvfb prefers to have one GUI app at a time – at least on travis.

I've seen flakiness go WAY down with these changes.

**Comment by matanlurey** [comment]
Dartium and Content Shell have been removed from the SDK.

**Comment by grouma** [comment]
Note that we do support a retry tag:  https://github.com/dart-lang/test/blob/master/doc/configuration.md#retry
