### ISSUE TITLE
Changing window.location causes test to hang 

### ISSUE THREAD

**Issue by srawlins** [dart-lang/test#562]
This might be expected, but I thought I'd open a bug in case. Take this Dart:

```dart
@TestOn('browser')
import 'package:test/test.dart';
import 'dart:html';

void main() {
  test('x', () {
    window.location.hash = 'seven';
  });
}
```

Run through test: `pub run test -p dartium b.dart` (can replace dartium with content-shell, chrome, ...). Test hangs.

**Comment by kevmoo** [comment]
One off brainstorm: could pkg/test at least listen for navigation events. Then could mark things as fail or cancel or something...

**Comment by nex3** [comment]
This is because we currently use the hrefs of incoming messages to determine which message corresponds to which worker. I'd really like to switch to using `MessageChannel`s instead, but they're hopelessly broken in Dart. If we can get https://github.com/dart-lang/sdk/issues/26349 and https://github.com/dart-lang/sdk/issues/26351 fixed, this will be really easy to fix as well.

**Comment by kevmoo** [comment]
Still blocked on https://github.com/dart-lang/sdk/issues/26351

**Comment by kevmoo** [comment]
Should be golden in `2.0.0-dev.44.0`+
