### ISSUE TITLE
Is package:test expected to pass tests on Mac?

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/test#566]
"no" is a fine answer, but if so we should add that to CONTRIBUTING.md.

Just trying to get the tests to pass so I can look at https://github.com/dart-lang/test/issues/36

My output:
https://gist.github.com/eseidelGoogle/e248f380cccc6b1e5ceb9d988bdfd46b

**Comment by kevmoo** [comment]
Sync. Just fixed :-)

**Comment by eseidelGoogle** [comment]
It also appears to leak content_shell processes.  They stay open after the test fails?  (And close when I stop the whole `pub run test`).

**Comment by eseidelGoogle** [comment]
I'm on dart-lang/test@7fa6d4bec9871bcc68ae5d9c74b57278971438cb which appears to be the latest @kevmoo?

**Comment by kevmoo** [comment]
Do you have content shell on your machine?

Use --with-content-shell w/ homebrew

**Comment by eseidelGoogle** [comment]
I appear to `/usr/local/bin/content_shell`  I installed --with-dartium, the README seems to suggest that that's enough? 
https://github.com/dart-lang/test/blob/master/README.md#running-tests-on-dartium

"The content shell is installed along with Dartium when using Homebrew."

**Comment by kevmoo** [comment]
Is content_shell in your path?

If so, maybe see if DART_SDK is exported, too?

export DART_SDK=`brew --prefix dart`/libexec

**Comment by kevmoo** [comment]
Just run on 7fa6d4bec9871bcc68ae5d9c74b57278971438cb on my mac

```
pub run test
00:01 +260: test/runner/browser/content_shell_test.dart: starts content shell with the given URL
  Skip: Failing with mysterious WebSocket issues.
01:58 +505 ~1: test/runner/hybrid_test.dart: spawnHybridCode() kills the isolate when the test closes the channel
  Skip: Enable when sdk#28081 is fixed.
01:58 +505 ~2: test/runner/hybrid_test.dart: spawnHybridCode() kills the isolate when the hybrid isolate closes the channel
  Skip: Enable when sdk#28081 is fixed.
06:02 +924 ~3: All tests passed!
```

**Comment by kevmoo** [comment]
@eseidelGoogle get back to this yet?

**Comment by grouma** [comment]
I have been running into issues getting all the tests to pass on my Linux box as well as my Mac. In a similar regard, I have found the tests that fail are a result of the Dartium process not being correctly shut down. I'll run the latest branch on my Mac and provide the ouput to get another data point.

**Comment by eseidelGoogle** [comment]
I ran them all again with 6c8cc9404cf1a1b453f8a411889eedd4cddbc8dd  got failures (and a ton of leaked darium processes).   I managed to clear my terminal before posting, so will need to run again.

%dartium --version                      [/src/package_test]
Chromium 45.0.2454.104  Dart 1.23.0-dev.5.0

%dart --version                         [/src/package_test]
Dart VM version: 1.23.0-dev.5.0 (Thu Mar  9 02:09:53 2017) on "macos_x64"

/usr/local/bin/content_shell -> ../Cellar/dartium/1.8.5/bin/content_shell

**Comment by grouma** [comment]
Pulling in the upstream changes has resolved my issues on Mac:

00:11 +264: test/runner/browser/content_shell_test.dart: starts content shell with the given URL   
  Skip: Failing with mysterious WebSocket issues.
07:30 +555 ~1: test/runner/hybrid_test.dart: spawnHybridCode() kills the isolate when the test closes the channel
  Skip: Enable when sdk#28081 is fixed.
07:30 +555 ~2: test/runner/hybrid_test.dart: spawnHybridCode() kills the isolate when the hybrid isolate closes the channel
  Skip: Enable when sdk#28081 is fixed.
16:20 +924 ~3: All tests passed!     

What version of content shell are you running? Note I'm using content_shell version 19.77.34.5 (34.5) which was installed along with Dartium since I used Homebrew. You can try manually updating the content_shell version by downloading the binary here: http://gsdview.appspot.com/dart-archive/channels/stable/release/latest/dartium/

This might resolve your issue.

**Comment by eseidelGoogle** [comment]
Turns out I had an ancient version of dartium.

**Comment by eseidelGoogle** [comment]
All tests are passing now.  I had to `brew uninstall --force dartium` to remove the ancient copies first before `brew install dart --with-dartium --with-content-shell` would work.  Supposedly the brew keg for dart doesn't support --overwrite as an arg.  :shrug:
