### ISSUE TITLE
A way to customize the expected/actual/which error output

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/test#738]
_See https://github.com/dart-lang/source_gen/issues/287 for (some) background._

I want to emit something like this on failure:

```
Expected:

class Foo$Generated {
  void a() {}
  void b() {}
}

Actual:

class Foo$Generated {
  void a() {}
}

Which:

* Missed an expected method, "b", in class "Foo$Generated":

<EXAMPLE OF EXPECTATION VERSUS REALITY PRINTED HERE>
```

**tl;dr**: I want to either silence or customize the "Actual: ..." part of the error reporting.

In my case, it is misleading, because the "actual" (`String`) needs to be formatted before comparing with the "expected" (`String`), but there isn't a way (I've found) to do this. Please let me know if I'm missing something.

**Comment by nex3** [comment]
I think this is (broadly) covered under https://github.com/dart-lang/matcher/issues/40. My general plan there is to give matchers much more control over the output they produce, so that they basically return the entire string that's printed by `expect()`, and then provide infrastructure to make it easy for custom matchers to produce good formatting by default.
