### ISSUE TITLE
How should I write an integration test?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/test#765]
Source of inspiration: https://github.com/dart-lang/angular/issues/511

I'd like to write an integration test, for travis (but also locally) that basically does:

* `cd examples/tiny_app`
* `pub run build_runner serve`
* `chrome localhost:8000`
* _some expectations here_
* _shutdown_

I'd like to write the actual instrumentation in Dart, as a `package:test`, test. Is this where the "hybrid"-esque tests are appropriate? What do you recommend for me to do, other than writing shell scripts or using something in Node?

**Comment by natebosch** [comment]
We do this type of thing in build/e2e_example

https://github.com/dart-lang/build/blob/master/e2e_example/test/build_integration_test.dart

We have methods to run the build, and then we typically have separate tests which we run in an 'inner' test which launches chrome etc. https://github.com/dart-lang/build/blob/6a7287712fce6aeba5ff78eefd90ea262ffa1c47/e2e_example/test/common/utils.dart#L197

**Comment by nex3** [comment]
I believe most people use [the `webdriver` package](https://pub.dartlang.org/packages/webdriver) for situations like this, which drives the browser instance and all expectations from within a VM Dart process.

You could hypothetically use hybrid tests instead by pointing an iframe at the app, but due to origin restrictions your communication may be limited to `postMessage()` which is pretty restrictive.

**Comment by matanlurey** [comment]
Thanks!
