### ISSUE TITLE
Reporter default varies across platforms

### ISSUE THREAD

**Issue by Hixie** [dart-lang/test#847]
I got confused recently because the default reporter is different on Windows (-rexpanded) than on other platforms (-rcompact).

We should either document this more clearly (including e.g. in the --help text), including the reasoning, or, even better if possible, make the default consistent throughout.

**Comment by jakemac53** [comment]
Fwiw, I checked with the regular command prompt on my windows box and the compact reporter seems to work fine, so I don't think there is a technical limitation.

I also noticed that the colors appear to be turned off on windows.

**Comment by jakemac53** [comment]
@nex3 are there any outstanding issues you know of with the compact reporter on windows?

**Comment by nex3** [comment]
I know we changed some details about how the VM prints output on Windows since these defaults were decided, so it's plausible that the compact reporter works now.

**Comment by jakemac53** [comment]
Both colors and the compact reporter seem to work on my windows box with the built in command prompt and in the vscode console, and the compact reporter appears to work on appveyor as well [before](https://ci.appveyor.com/project/kevmoo/build/build/1.0.1795) - [after](https://ci.appveyor.com/project/kevmoo/build/build/1.0.1796). I think the appveyor log viewer just doesn't respect colors, because its going through the same logic to determine if it should use colors.

I changed all the windows detection logic to instead use `stdout.supportsAnsiEscapes`. We could also simply check if its a terminal but I think this is better? There are some scenarios I believe where that doesn't get recognized properly though.

**Comment by jakemac53** [comment]
This is changed and published - we will keep an eye out for any users reporting that they lost the compact reporting and/or colors and file corresponding issues on the SDK to get better support for `stdout.supportsAnsiEscapes` (it has relatively basic rules right now).
