### ISSUE TITLE
`kill (pid)` doesn't seem terminate VM for a long time when awaiting in a test

### ISSUE THREAD

**Issue by DanTup** [dart-lang/test#891]
This one is weird and I'm not sure if it's test, pub or the VM causing it. I can't repro in a simple VM script, only in a test, so I'm starting here but let me know if you think this is a pub or VM issue.

I'm trying to ensure when you hit Stop during a test run in VS Code that we terminate the test run process correctly. Sometimes, everything works fine. However, sometimes the test process does not quit when I send a kill signal (in my test case, I'm awaiting a delayed future for testing). I can reproduce this using `kill` from the terminal (which sends ` SIGTERM`, the same as I'm doing in Dart Code).

Example test:

```dart
void main() {
  group("String", () {
    test("TEST", () async {
      await new Future<void>.delayed(const Duration(seconds: 600));
    });
```

I ran this test using `pub run test` then used `ps` to get it's `pid` and then issued a kill from the terminal. Over 20 seconds later the process is still alive.

```bash
$ ps -ax | grep pub.
13610 ??         0:02.06 /Users/dantup/Dev/dart-sdk/v2/bin/dart /Users/dantup/Dev/dart-sdk/v2/bin/snapshots/pub.dart.snapshot run test -r json -j1 test/basic_test.dart

$ kill 13610; sleep 20; ps -ax | grep pub.dart
13610 ??         0:02.09 /Users/dantup/Dev/dart-sdk/v2/bin/dart /Users/dantup/Dev/dart-sdk/v2/bin/snapshots/pub.dart.snapshot run test -r json -j1 test/basic_test.dart
```

It doesn't seem like the process lives for the full 600 seconds, but it definitely lives for a lot longer than it seems like it should. I don't know if the issue is isolated to waiting with dummy futures like this or if it would happen for things like I/O (I couldn't find a way to make one take long enough to let me test it reliably).

I'm testing with `2.0.0-dev.63.0` and `test: 1.0.0`.

**Comment by jakemac53** [comment]
I believe that the test runner intercepts these signals to attempt to allow all currently running tests to complete before exiting - presumably this is to help ensure that tests are allowed to clean up any resources they are using (basically, make sure we execute `tearDown`/`tearDownAll`). Otherwise you could easily end up with temp directories that aren't cleaned up or even rogue processes in the worst case.

You probably see it not waiting the full 600 seconds because it times out before that happens.

**Comment by jakemac53** [comment]
@natebosch @grouma what are your opinions on this? Working as intended or is there something we should try and do here?

- We could add configuration to make it not intercept these calls but that would mean not cleaning up resources and cause other issues.
- We could look into eagerly executing `tearDown`/`tearDownAll`, basically treat it like an immediate timeout, but the running tests could still be executing arbitrary code and this could cause all kinds of weird errors, especially on windows where deleting a directory with a currently running process in it will fail anyways.
- We could try and add events to the json reporter so that we can inform it of the currently running tests so there is at least the option to provide some feedback in the ui.

@DanTup fwiw the "workaround" here is to just send two kill signals, on the second one package:test will actually exit. However this is really not a good idea to do as a part of any sort of standard workflow due to the issues mentioned.

**Comment by DanTup** [comment]
I thought that might be the case, and it makes sense to run the cleanups - but I don't understand why it's taking so long. The result is that the user clicks Stop in the editor, and it takes a long time for the debug session to end.

Do you know how it's hooking these? Maybe I can add some logging to see where the time is going.

**Comment by DanTup** [comment]
Oh, I see - it's probably this here:

https://github.com/dart-lang/test/blob/69fb67eab0b3c3622440379cd844fc4e5de1603a/lib/src/executable.dart#L31

I'll so some testing. It doesn't seem like it should take > 20 seconds to clean up a test that didn't do anything.

**Comment by jakemac53** [comment]
> I thought that might be the case, and it makes sense to run the cleanups - but I don't understand why it's taking so long. The result is that the user clicks Stop in the editor, and it takes a long time for the debug session to end.

It is waiting for the test to finish, in this case that means waiting for a timeout. It isn't safe for it to jump right to `tearDown` or `tearDownAll` because the test is still running.

**Comment by DanTup** [comment]
Aha:

> Waiting for current test(s) to finish.
> Press Control-C again to terminate immediately.

This doesn't explain why it seemed like less than 600 seconds, but it does explain why it's slow. Maybe this should be conditional based on whether it's running in json mode, or there should be another flag? (it should still clean up, but not wait for a test).

Or, maybe there should at least be some way of routing a message back in the JSON so we can display an equiv message to the user that we're waiting for a test to finish.

**Comment by jakemac53** [comment]
(and yes, even the timeout case already has these issues I mentioned but at least we are giving the test a reasonable and configurable amount of time to finish in that case)

**Comment by jakemac53** [comment]
> Is it not possible to terminate the test that's running? (so it behaves the same as if it threw)?

Not easily. Technically, we might be able to do something with zones but it would require intercepting every single async task that is scheduled and wrapping it in a method that would bail early if it detected this state.

**Comment by DanTup** [comment]
Thanks for the info - I think we can close this since it's a bit off the mark. Let me know if you think adding the ability to route the above message over the JSON API is worthwhile (and makes sense) and I can open another. For now I'll try and handle it better at the editor side.
