### ISSUE TITLE
Set up CI on appveyor

### ISSUE THREAD

**Issue by natebosch** [dart-lang/test#920]

**Comment by DanTup** [comment]
I had a quick go at this - I copied the Travis script and tweaked for Windows:

https://ci.appveyor.com/project/DanTup/test/build/1.0.2

It's currently running - some tests have passed but PhantomJS started throwing. I'll check back on it later to see how it ended up. If the browser tests aren't easy to fix (I don't know, maybe the will be) then running the non-browser tests on AppVeyor is probably still a reasonable step.

**Comment by DanTup** [comment]
I fixed missing PhantomJS, current results are here:

https://ci.appveyor.com/project/DanTup/test

Lots of failures due to cleanup failing to delete files ("The process cannot access the file because it is being used by another process") which is strange as it runs after `.exitCode` completes (and doesn't happen on my Windows box). Also some weird things like "TimeoutException after 0:00:00.000000: Test timed out after 0 seconds.".

Is there a way to run without any of the browser tests to start with? Having just the VM tests run would have value

**Comment by jakemac53** [comment]
We should be able to just pass `-p vm` to run all the vm tests.

**Comment by DanTup** [comment]
> We should be able to just pass `-p` vm to run all the vm tests.

I tried this:

```pub run test -p vm --preset travis --total-shards 5 --shard-index %SHARD_INDEX%```

However it still seems to be failing on PhantomJS:

https://ci.appveyor.com/project/DanTup/test/build/job/q0u0h6w7vwd3xrft

```
01:03 +64: test\runner\browser\phantom_js_test.dart: starts PhantomJS with the given URL
CreateProcessW failed 2
01:03 +64 -1: loading test\runner\browser\runner_test.dart
01:03 +64 -1: test\runner\browser\phantom_js_test.dart: starts PhantomJS with the given URL [E]
  Failed to run PhantomJS: The system cannot find the file specified.
```

Any ideas?

**Comment by jakemac53** [comment]
It might be that `--preset travis` is overriding the platforms?

**Comment by DanTup** [comment]
Ah, turned out the test that's failing is a VM test (I guess because it runs on the VM, to spawn PhantomJS):

> test\runner\browser\phantom_js_test.dart: starts PhantomJS with the given URL

```
@TestOn("vm")
@Tags(const ["phantomjs"])
```

So I've used `--exclude-tags` to exclude `phantomjs` which seems to have worked. However, the cleanup code fails because, well, Windows 🤷‍♂️

```
FileSystemException: Deletion failed, path = 'C:\Users\appveyor\AppData\Local\Temp\1\dart_test_220185e2-a55c-11e8-81ff-00155dfb5aa7' (OS Error: The process cannot access the file because it is being used by another process.
  , errno = 32)
```

Is it reasonable to swallow these exceptions on Windows in the test cleanup?

**Comment by natebosch** [comment]
In the short term I would prefer to go with `--exclude-tags` and see if we can figure out a way to make sure it is cleaned up properly.

**Comment by DanTup** [comment]
I've used the `--exclude-tags` to exclude the ones trying to spawn PhantomJS, but I think Windows sucks at letting you delete files right after their locks were closed (Flutter's tests now have catch blocks that just `print` when this happens).

I'll try and do a little more testing though, it's possible it's not releasing it properly (or that a small delay or retry might fix it).

**Comment by jakemac53** [comment]
> but I think Windows sucks at letting you delete files right after their locks were closed

Ya we see this in the scratch space stuff as well... had to add retries with exponential backoff to resolve it, and that doesn't work a surprisingly large amount of the time either :(.

**Comment by DanTup** [comment]
Yeah, I found this code in pub:

https://github.com/dart-lang/pub/blob/5962908a66e814dd78f6856a4e5f792c6db65fbc/lib/src/io.dart#L315

Do you want me to add something similar here? (And if so, do we still want to fail the tests if all retries finish)?

**Comment by natebosch** [comment]
We have windows tests in github actions now.
