### ISSUE TITLE
integration test error

### ISSUE THREAD

**Issue by erwintan96** [dart-lang/test#964]
DriverError: Could not determine URL to connect to application.
  Either the VM_SERVICE_URL environment variable should be set, or an explicit
  URL should be provided to the FlutterDriver.connect() method.
  Original error: null
  Original stack trace:
  null
      
  package:flutter_driver/src/driver/driver.dart 208:7  FlutterDriver.connect
  ===== asynchronous gap ===========================
  dart:async                                           _AsyncAwaitCompleter.completeError
  package:flutter_driver/src/driver/driver.dart        FlutterDriver.connect

Hi sir, could you help me? is this a bug from the library or not? And do you know how to fix this?
because i read https://github.com/flutter/flutter/issues/15433 and they have no idea like me and i can't find the solution on google too..

**Comment by jakemac53** [comment]
This looks like something flutter specific, so I am going to close the issue here.

That being said it looks like this should be getting set here https://github.com/flutter/flutter/blob/938dd5a4aa9cdeff973f238dce2ed0a77e3730d5/packages/flutter_tools/lib/src/commands/drive.dart#L298.

Are you running the tests using the flutter tools? They won't work via a normal `pub run test` for instance I don't think.
