### ISSUE TITLE
Tests fail if futures created within them reject without assertions

### ISSUE THREAD

**Issue by moodysalem** [dart-lang/test#981]
The test runner asserts that futures created within the test complete, unless an expectation is set that they should fail

```dart
    test('futures', () {
      final first = Future.delayed(Duration(milliseconds: 100), () => 'abc');
      final second =
          Future.delayed(Duration(milliseconds: 100), () => throw Error());

      expect(first, completion('abc'));
//      expect(second, throwsA((error) => error is Error));
    });
```
This test fails indicating an error was thrown by second. Uncommenting the line causes the test to pass.

This is a usability problem for a few reasons:

1. I have to make assertions that may not be relevant to the specific behavior I'm trying to test
2. Where I make the assertion depends on the implementation of the test package. If the future rejects before the expectation is set, the test fails.
3. ~It's inconsistent - `Future.error` does not have the same problem~ this is not true-`Future.error` shares the same behavior
4. It's inconsistent with how JavaScript test frameworks work, e.g. mocha/jest

**Comment by grouma** [comment]
This is expected behavior and is documented: https://github.com/dart-lang/test/blob/master/pkgs/test/README.md#asynchronous-tests

Some comments:

> 1. I have to make assertions that may not be relevant to the specific behavior I'm trying to test

We capture any asynchronous tasks initiated by your test code. I'd argue that errors coming from these tasks are relevant to your tests. Without this feature I do not see how one can have confidence that their asynchronous code executes without error.

> 2.  Where I make the assertion depends on the implementation of the test package. If the future rejects before the expectation is set, the test fails.

I'm not sure I follow this one. Are you familiar with `expectLater`: https://github.com/dart-lang/test/blob/f87d414e53f2e878f3fd2c0f0237cebdaaa46f80/pkgs/test_api/lib/src/frontend/expect.dart#L74 It provides more flexibility.

> 3.  It's inconsistent - `Future.error` does not have the same problem

Not sure I follow this one either. Can you explain exactly what is inconsistent?

> 4. It's inconsistent with how JavaScript test frameworks work, e.g. mocha/jest

Dart has the concept of Zones (https://www.dartlang.org/articles/libraries/zones) baked into the language which enables this sort of functionality. As far as I know there is no equivalent in Javascript which is likely one of the reasons corresponding frameworks do not have this feature. Also consistency with Javascript frameworks is not a stated goal of this package.

**Comment by moodysalem** [comment]
In the linked documentation nowhere does it say (afaict) that any future created within the test must also complete without error (vs. only the returned future having to complete without error).

> I'd argue that errors coming from these tasks are relevant to your tests.

Not necessarily in a single unit test. Say method A returns a future and has some side effect. I might have one test to validate side effect X of a method A and another test to validate the return value of method A. Because of the expectation that all futures created resolve, I have to make assertions that may not be relevant to the behavior I'm trying to test when I test side effect X.

> Where I make the assertion depends on the implementation of the test package. If the future rejects before the expectation is set, the test fails.

This is specific to the dart test package. Here's an example:
```dart
  test('thing', () async {
    Completer completer = Completer();
    completer.completeError(Error());
    await Future.delayed(Duration(milliseconds: 100));
    expect(completer.future, throwsA((error) => error is Error));
  });
```

One might expect this test to succeed, but it fails. Reverse the order of the await and expect and it works. It's a separate problem but it's part of the problem that I have to make assertions on futures I don't necessarily care about in a specific test.

> Dart has the concept of Zones (https://www.dartlang.org/articles/libraries/zones) baked into the language which enables this sort of functionality. As far as I know there is no equivalent in Javascript which is likely one of the reasons corresponding frameworks do not have this feature. Also consistency with Javascript frameworks is not a stated goal of this package.

Even if this is a technical restriction in those languages, there is value in the dart test package having behavior consistent with other languages in its target platforms. I also don't know if this implicit behavior would be desirable by users of those test frameworks, because it limits your ability to split tests by behavior as above.

**Comment by grouma** [comment]
Sorry, I didn't provide the correct documentation. The documentation resides here:
https://github.com/dart-lang/test/blob/f87d414e53f2e878f3fd2c0f0237cebdaaa46f80/pkgs/test_api/lib/src/frontend/expect.dart#L50

> /// Certain matchers, like [completion] and [throwsA], either match or fail
/// asynchronously. When you use [expect] with these matchers, it ensures that
/// the test doesn't complete until the matcher has either matched or failed. If
/// you want to wait for the matcher to complete before continuing the test, you
/// can call [expectLater] instead and `await` the result.

I fiddled with your initial example a little more to fully understand what's happening. Basically, your test is kept "open" due to the `completion` matcher and an uncaught (asynchronous) error is thrown before the test completes. However, on my machine your provided example passes due to different timing mechanics. I have to play with the durations to ensure the error is thrown prior to the test completion. 

> Where  I make the assertion depends on the implementation of the test package. If the future rejects before the expectation is set, the test fails.

This boils down to the fact that your error is either properly handled or not. I can understand wanting to limit the number of expects within a unit test. I can see potentially adding some functionality to ignore unhandled asynchronous errors (although I'm not sure exactly how that would look). As an alternative you can handle the errors yourself with something like this:

```
test('futures', () async {
    await runZoned(() {
      final first = Future.delayed(Duration(milliseconds: 100), () => 'abc');
      final second =
          Future.delayed(Duration(milliseconds: 100), () => throw Error());

      expect(first, completion('abc'));
    }, onError: (e) {
      // Ignore expected async errors
      if (e is Error) return;
      // Forward test errors
      if (e is TestFailure) throw e;
    });
  });
```

**Comment by moodysalem** [comment]
I'm not sure this is necessarily an issue actually-in the synchronous case, if I expected a method to throw, I would wrap it in a try/catch that did nothing. I can just add a catch to my future and do nothing with it, so I'm not required to write an `expect`. I think in hindsight it probably is beneficial to the developer to require them to explicitly check their futures do not reject. Thanks!
