### ISSUE TITLE
Problem with isNot and throwsException matching behaviour 

### ISSUE THREAD

**Issue by freitzzz** [dart-lang/test#996]
Good afternoon everyone.

I've been trying to combine the behaviour between isNot and throwsException matchers, but they don't seem to workout.
Shouldn't `throwsException` detect if any kind of exception is thrown and isNot ***negate*** the detection, in order to match that an expression is not supposed to throw an exception?

I've been investigating other issues and noticed it was also mentioned in the past  but was never released iiuc.
https://github.com/dart-lang/test/issues/539
https://github.com/dart-lang/test/pull/541

My Dart version is `2.1.0 (Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297))` which is integrated with Flutter 1.0.0
Tests runned on: `Linux x64 / Lubuntu`

**Comment by natebosch** [comment]
It looks like it works for synchronous stuff: `expect(() {}, isNot(throwsA(anything)));` passes for me.

What doesn't work is `expect(Future.value(), isNot(throwsA(anything)));`

The workaround is to do `expect(someFuture, returnsNormally);` or even `expect(await someFuture, anything));` Will one of those options work for you? Making `isNot` seamlessly handle async matching would not be easy.

**Comment by freitzzz** [comment]
Good point @natebosch ! I forgot to mention that I was testing an asynchronous operation.

Thanks for the info regarding in which condition it works :) 

Also, will Dart-Test team make it work for asynchronous operations? And if not, is there a particular reason for it?

Cheers,
freitzzz

**Comment by natebosch** [comment]
> will Dart-Test team make it work for asynchronous operations?

Unfortunately probably not.

> And if not, is there a particular reason for it?

It would require making `isNot` more aware of asynchronous matchers, and really ramp up the complexity. I haven't investigated very deeply to understand how much, or whether it would end up being in feasible without a breaking change.

Since the alternatives exist and are more readable I don't think it's likely we'll want to invest in this area. The sharp edges of being unable to use a pattern that you expect to work aren't great - but I don' t think the pain outweighs the complexity in making it all work for async stuff.
